# 监控任务数据上传消息
string id_task_info          # 任务信息ID
string task_ticket           # 任务票据
string monitor_points        # 监控点位
float32 ch4_data             # CH4数据
float32 temp_data            # 温度数据
float32 hum_data             # 湿度数据
string img_vis_file_name     # 可见光图像文件名
string img_vis_md5_value     # 可见光图像MD5值
string img_ir_file_name      # 红外图像文件名
string img_ir_md5_value      # 红外图像MD5值
string img_3d_file_name      # 3D图像文件名
string img_3d_md5_value      # 3D图像MD5值